version: 2.1

jobs:
  run-tests:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          command: "git submodule update --init --recursive"
      - run:
          command: "sudo apt update && sudo apt install g++ scons"
      - run:
          command: "scons --no-cache -j2 && ./build/test"

workflows:
  test-workflow:
    jobs:
      - run-tests
